Add boot-test CI job

diff --git a/.github/workflows/ImageBuild.yaml b/.github/workflows/ImageBuild.yaml
--- a/.github/workflows/ImageBuild.yaml
+++ b/.github/workflows/ImageBuild.yaml
@@ -7,7 +7,6 @@ on:
       - "**/*.nix"
 
 jobs:
-
   build-image:
     name: Build dev image
     runs-on: ubuntu-latest
@@ -52,12 +51,52 @@ jobs:
         with:
           path: output
           key: output
+  boot-test:
+    runs-on: ubuntu-latest
+    needs: build-image
+
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v2
+
+      - name: Install QEMU and other dependencies
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y qemu-system-aarch64 wget unzip
+
+      - name: Load Image Cache
+        id: cache-image
+        uses: actions/cache@v3
+        with:
+          path: output
+          key: output
+
+      - name: Boot Raspberry Pi Image
+        env:
+          TAG_NAME: ${{needs.build-image.outputs.tag-name}}
+          ISO_NAME: ${{needs.build-image.outputs.iso-name}}
+        run: |
+          qemu-system-aarch64 \
+            -machine type=raspi4
+            -m 2G \
+            -kernel kernel8.img \
+            -append "rw earlyprintk loglevel=8 console=ttyAMA0,115200 dwc_otg.lpm_enable=0 root=/dev/mmcblk0p2" \
+            -sd output/$ISO_NAME \
+            -dtb bcm2711-rpi-4-b.dtb \
+            -no-reboot \
+            -serial stdio  | tee boot.log
+          if grep -q "Reached target Multi-User System." boot.log; then
+            echo "Booted successfully!"
+          else
+            echo "Failed to boot!"
+            exit 1
+          fi
 
   release-image:
     permissions:
       contents: write
     name: Release Image
-    needs: build-image
+    needs: boot-test
     if: github.ref_name == 'main'
     runs-on: ubuntu-latest
     steps:
